---
name: Integration

on:
  workflow_call:
    inputs:
      distros:
        required: false
        description: "List of distributions to test against the Role"
        type: string
        default: '[ "debian11", "debian10" ]'
      python-dependencies:
        required: false
        description: "Default pip dependencies for molecule"
        type: string
        default: |
          molecule[docker]==3.6.1
          molecule-goss
          jmespath
      role-dependencies:
        required: false
        description: "Default role dependencies for ansible (empty)"
        type: string
        default: ""
      molecule-config:
        required: false
        description: "Configuration for molecule"
        type: string
        default: |
          ---
          driver:
            name: docker
          platforms:
            - name: instance
              image: "geerlingguy/docker-\$\{MOLECULE_DISTRO:-debian11\}-ansible:latest"
              command: ${MOLECULE_DOCKER_COMMAND:-""}
              volumes:
                - /sys/fs/cgroup:/sys/fs/cgroup:ro
              privileged: true
              pre_build_image: true
          provisioner:
            name: ansible
            playbooks:
              converge: ../default/converge.yml
      disable-apparmor-mysql:
        required: false
        description: "Disable AppArmor MySQL Profile for the Job Runner"
        type: boolean
        default: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6

      - name: YAMLLint
        uses: ibiqlik/action-yamllint@v3

  test:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro: ${{ fromJSON(inputs.distros) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup yq
        uses: mikefarah/yq@v4.29.2

      - name: Prepare Molecule Tests
        run: |
          # Creating required directories
          mkdir -p molecule/github
          # Writing required packages to requirements.txt (to cached)
          echo "${{ inputs.python-dependencies }}" > molecule/requirements.txt
          # Writing molecule config for docker
          echo "${{ inputs.molecule-config}}" > molecule/github/molecule.yml
          # Writing ansible role requirements
          echo "${{ inputs.role-dependencies }}" > molecule/requirements.yml

          # Add prepare playbook if exists
          if test -f "molecule/default/prepare.yml"; then
            yq e --inplace '.provisioner.playbooks += {"prepare":"../default/prepare.yml"}' molecule/github/molecule.yml
          fi

          # Add verify playbook if exists
          if test -f "molecule/default/verify.yml"; then
            yq e --inplace '.provisioner.playbooks += {"verify":"../default/verify.yml"}' molecule/github/molecule.yml
            yq e --inplace '. += {"verifier": {"name": "goss", "directory": "../default/tests/"}}' molecule/github/molecule.yml
          fi

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "molecule/requirements.txt"

      - name: Install Dependencies
        run: pip3 install -r molecule/requirements.txt

      - name: Install Ansible Role Requirements
        run: ansible-galaxy install -r molecule/requirements.yml
        if: inputs.role-dependencies != ''

      - name: Disable AppArmor (MySQL)
        run: |
          set -x
          sudo apt-get install apparmor-profiles
          sudo apparmor_status
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
          sudo apparmor_status
        if: inputs.disable-apparmor-mysql

      - name: Print Molecule debug information
        run: |
          echo "Print molecule/requirements.txt"
          cat molecule/requirements.txt
          echo "Print molecule/github/molecule.yml"
          cat molecule/github/molecule.yml
          echo "Print molecule/default/converge.yml"
          cat molecule/default/converge.yml
          if [ -f "molecule/default/prepare.yml" ]; then echo "Print molecule/default/prepare.yml" && cat molecule/default/prepare.yml; fi
          if [ -f "molecule/default/verify.yml" ]; then echo "Print molecule/default/verify.yml" && cat molecule/default/verify.yml; fi

      - name: Molecule Test
        run: molecule test -s github
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
